version: 2

updates:
  # FastAPI (Python)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

  # Flutter (Dart)
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
