# -*- coding: utf-8 -*-
import os

lines = [
    "import 'app_localizations_en.dart';",
    "",
    "class AppLocalizationsAr extends AppLocalizationsEn {",
    "  @override String get appTitle => 'عالم كيندر';",
    "  @override String get welcome => 'مرحبا';",
    "  @override String get next => 'التالي';",
    "  @override String get back => 'رجوع';",
    "  @override String get continueText => 'متابعة';",
    "  @override String get skip => 'تخطي';",
    "  @override String get done => 'تم';",
    "  @override String get cancel => 'إلغاء';",
    "  @override String get save => 'حفظ';",
    "  @override String get delete => 'حذف';",
    "  @override String get edit => 'تعديل';",
    "  @override String get loading => 'جاري التحميل...';",
    "  @override String get error => 'خطأ';",
    "  @override String get connectionError => 'خطأ في الاتصال. حاول مرة أخرى.';",
    "  @override String get success => 'نجاح';",
    "  @override String get retry => 'إعادة المحاولة';",
    "  @override String get noInternet => 'لا يوجد اتصال بالإنترنت';",
    "  @override String get offlineMode => 'وضع عدم الاتصال';",
    "  @override String get splashTagline => 'تعلّم. العب. انمو.';",
    "  @override String get login => 'تسجيل الدخول';",
    "  @override String get register => 'إنشاء حساب';",
    "  @override String get email => 'البريد الإلكتروني';",
    "  @override String get parentEmail => 'البريد الإلكتروني لولي الأمر';",
    "  @override String get parentEmailNotFound => 'البريد الإلكتروني لولي الأمر غير موجود. يرجى تسجيل الدخول بولي الأمر أولاً.';",
    "  @override String get password => 'كلمة المرور';",
    "  @override String get confirmPassword => 'تأكيد كلمة المرور';",
    "  @override String get forgotPassword => 'نسيت كلمة المرور؟';",
    "  @override String get parentLogin => 'دخول ولي الأمر';",
    "  @override String get childLogin => 'دخول الطفل';",
    "  @override String get childId => 'رقم الطفل';",
    "  @override String get picturePassword => 'كلمة مرور الصور';",
    "  @override String get selectPicturePassword => 'اختر كلمة مرور الصور';",
    "  @override String get confirmPicturePassword => 'تأكيد كلمة مرور الصور';",
    "  @override String get deleteChildTitle => 'حذف ملف الطفل';",
    "  @override String get deleteChildDescription => 'سيؤدي هذا إلى حذف ملف الطفل وجميع البيانات المرتبطة به بشكل دائم. لا يمكن التراجع عن هذا الإجراء.';",
    "  @override String get deleteChildSuccess => 'تم حذف ملف الطفل بنجاح';",
    "  @override String get deleteChildFailed => 'فشل حذف ملف الطفل';",
    "  @override String get activeLabel => 'نشط';",
    "  @override String get yourPlanIncludes => 'خطتك تشمل:';",
    "  @override String planChildProfiles(int count) => 'حتى $count ملف طفل';",
    "  @override String get unlimitedActivities => 'أنشطة غير محدودة';",
    "  @override String get advancedReportsLabel => 'تقارير متقدمة';",
    "  @override String get offlineDownloadsLabel => 'تنزيلات دون اتصال';",
    "  @override String get prioritySupportLabel => 'دعم أولوية';",
    "  @override String get billingInformation => 'معلومات الفوترة';",
    "  @override String get nextPayment => 'الدفعة التالية';",
    "  @override String get amountLabel => 'المبلغ';",
    "  @override String get paymentMethodLabel => 'طريقة الدفع';",
    "  @override String get manageBilling => 'إدارة الفوترة';",
    "  @override String get availablePlans => 'الخطط المتاحة';",
    "  @override String get recommendedLabel => 'موصى به';",
    "  @override String get currentPlanLabel => 'الخطة الحالية';",
    "  @override String get processingLabel => 'جارٍ المعالجة...';",
    "  @override String get choosePlanLabel => 'اختر الخطة';",
    "  @override String get basicFeaturesOnly => 'الميزات الأساسية فقط';",
    "  @override String get bestForFamilies => 'الأفضل للعائلات';",
    "  @override String get limitedActivities => 'أنشطة محدودة';",
    "  @override String get oneChildProfile => 'ملف طفل واحد';",
    "  @override String get upToThreeChildren => 'حتى 3 أطفال';",
    "  @override String get paletteDefault => 'الافتراضي';",
    "  @override String get paletteOceanBlue => 'أزرق المحيط';",
    "  @override String get palettePurpleNight => 'ليلة أرجوانية';",
    "  @override String get paletteForestGreen => 'أخضر الغابة';",
    "  @override String get paletteSunsetOrange => 'برتقالي الغروب';",
    "  @override String buildLabel(String buildNumber) => 'الإصدار $buildNumber';",
    "  @override String get subscriptionActivationFailed => 'فشل تفعيل الاشتراك.';",
    "  @override String planActivated(String planName) => 'تم تفعيل خطة $planName.';",
    "  @override String get nextPaymentSampleDate => '31 ديسمبر 2024';",
    r"  @override String get sampleAmountPerMonth => '9.99\$/شهر';",
    "  @override String get samplePaymentMethod => '**** **** **** 1234';",
    "  @override String get billingTitle => 'الفوترة';",
    "  @override String get billingComingSoon => 'إدارة الفوترة قادمة قريباً. يمكنك تحديث طرق الدفع والفواتير هنا بمجرد أن يكون الخادم جاهزاً.';",
    "  @override String get resetPassword => 'إعادة تعيين كلمة المرور';",
    "  @override String get parentAccount => 'حساب ولي الأمر';",
    "  @override String get forgotYourPassword => 'نسيت كلمة المرور؟';",
    "  @override String get forgotPasswordDescription => 'لا تقلق! أدخل بريدك الإلكتروني وسنرسل لك رابطاً لإعادة تعيين كلمة المرور.';",
    "  @override String get emailAddress => 'عنوان البريد الإلكتروني';",
    "  @override String get emailPlaceholder => 'parent@email.com';",
    "  @override String get emailValidationEmpty => 'يرجى إدخال بريدك الإلكتروني';",
    "  @override String get emailValidationInvalid => 'يرجى إدخال بريد إلكتروني صحيح (Gmail، Outlook، إلخ)';",
    "  @override String get spamFolderNote => 'تحقق من مجلد البريد العشوائي إذا لم تجد الرسالة خلال دقائق.';",
    "  @override String get sendResetLink => 'إرسال رابط الإعادة';",
    "  @override String get backToLogin => 'العودة لتسجيل الدخول';",
    "  @override String get checkYourInbox => 'تحقق من بريدك الوارد!';",
    r"  @override String resetLinkSentTo(String email) => 'أرسلنا رابط إعادة تعيين كلمة المرور إلى\n$email';",
    "  @override String get step1OpenEmail => 'افتح البريد الإلكتروني من كيندر وورلد';",
    "  @override String get step2ClickLink => 'انقر على رابط إعادة تعيين كلمة المرور';",
    "  @override String get step3CreatePassword => 'أنشئ كلمة مرورك الجديدة';",
    "  @override String get didntReceiveIt => 'لم تستلمه؟ حاول مرة أخرى';",
    "  @override String get needHelp => 'تحتاج مساعدة؟';",
    "  @override String get wellAskYourParent => 'سنسأل والديك!';",
    "  @override String get forgotYourPictures => 'نسيت صورك؟';",
    "  @override String get forgotPicturesDescription => 'لا مشكلة! أخبرنا برقم الطفل وبريد والديك. سنرسل لهم رسالة لمساعدتك.';",
    "  @override String get yourChildId => 'رقم الطفل الخاص بك';",
    "  @override String get childIdHint => 'مثال: أميرة123';",
    "  @override String get childIdRequired => 'يرجى إدخال رقم الطفل';",
    "  @override String get parentsEmail => 'بريد ولي الأمر';",
    "  @override String get parentEmailHint => 'parent@email.com';",
    "  @override String get parentEmailRequired => 'يرجى إدخال بريد ولي الأمر';",
    "  @override String get parentEmailInvalid => 'يرجى إدخال بريد إلكتروني صحيح';",
    "  @override String get parentWillGetEmail => 'سيحصل والديك على بريد إلكتروني ويمكنهم مساعدتك في تسجيل الدخول!';",
    "  @override String get askParentForHelp => 'اطلب المساعدة من ولي الأمر';",
    "  @override String get backToChildLogin => 'العودة لدخول الطفل';",
    "  @override String get messageSentTitle => 'تم إرسال الرسالة!';",
    r"  @override String messageSentToParent(String email) => 'أرسلنا رسالة لوالديك على\n$email';",
    "  @override String get whatHappensNext => 'ماذا يحدث بعد ذلك؟';",
    "  @override String get childStep1 => 'يحصل والديك على بريد إلكتروني منا';",
    "  @override String get childStep2 => 'سيساعدونك في تعيين كلمات مرور صور جديدة';",
    "  @override String get childStep3 => 'ستعود للعب في أقرب وقت!';",
    "  @override String get tryAgainDifferentInfo => 'حاول مرة أخرى بمعلومات مختلفة';",
    "  @override String get personalInformation => 'المعلومات الشخصية';",
    "  @override String get securitySection => 'الأمان';",
    "  @override String get accountCreatedWelcome => 'تم إنشاء الحساب! أهلاً بك في كيندر وورلد.';",
    "}",
]

out_path = os.path.join(
    os.path.dirname(__file__),
    "lib", "core", "localization", "l10n", "app_localizations_ar.dart"
)
with open(out_path, "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")

print("Written", out_path)
